name: Deploy Joliet-frontend
on:
push:
branches:
  - main
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
deploy:
  name: Deploy app
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./src/Web/frontend
  steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
